version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: TodoApi/Dockerfile.dev
    ports:
      - '${API_PORT}:8080'
    depends_on:
      - db
    environment:
      - DEFAULT_CONNECTION_STRING=${DB_CONNECTION_STRING}

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
